/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as SkillsRouteRouteImport } from './routes/skills/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as ArchiveIndexRouteImport } from './routes/archive/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as SkillsTechnologyRouteImport } from './routes/skills/technology'
import { Route as SkillsEnterpriseRouteImport } from './routes/skills/enterprise'
import { Route as SkillsDesignRouteImport } from './routes/skills/design'
import { Route as SkillsDataRouteImport } from './routes/skills/data'
import { Route as ProfileAcademicRouteImport } from './routes/profile/academic'
import { Route as LibraryMultitenancyRouteImport } from './routes/library/multitenancy'
import { Route as ExperimentalBook2RouteImport } from './routes/experimental/book2'
import { Route as ExperimentalBook1RouteImport } from './routes/experimental/book1'
import { Route as LibraryIndexRouteRouteImport } from './routes/library/index/route'
import { Route as ArchiveItemsRCLAStudioProcessAutomationRouteRouteImport } from './routes/archive/_items/RCLA-studio-process-automation/route'
import { Route as ArchiveItemsHK19Hack19RouteRouteImport } from './routes/archive/_items/HK19-hack19/route'
import { Route as ArchiveItemsDVISDataVisShowcaseRouteRouteImport } from './routes/archive/_items/DVIS-data-vis-showcase/route'
import { Route as ArchiveItemsCRSSCreditSuisseOsaRouteRouteImport } from './routes/archive/_items/CRSS-credit-suisse-osa/route'
import { Route as ArchiveItemsCEPLCarderRouteRouteImport } from './routes/archive/_items/CEPL-carder/route'
import { Route as ArchiveItemsALRNAileronRouteRouteImport } from './routes/archive/_items/ALRN-aileron/route'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRouteRoute = SkillsRouteRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillsRouteRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsTechnologyRoute = SkillsTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => SkillsRouteRoute,
} as any)
const SkillsEnterpriseRoute = SkillsEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => SkillsRouteRoute,
} as any)
const SkillsDesignRoute = SkillsDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => SkillsRouteRoute,
} as any)
const SkillsDataRoute = SkillsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SkillsRouteRoute,
} as any)
const ProfileAcademicRoute = ProfileAcademicRouteImport.update({
  id: '/profile/academic',
  path: '/profile/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMultitenancyRoute = LibraryMultitenancyRouteImport.update({
  id: '/library/multitenancy',
  path: '/library/multitenancy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentalBook2Route = ExperimentalBook2RouteImport.update({
  id: '/experimental/book2',
  path: '/experimental/book2',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentalBook1Route = ExperimentalBook1RouteImport.update({
  id: '/experimental/book1',
  path: '/experimental/book1',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRouteRoute = LibraryIndexRouteRouteImport.update({
  id: '/library/',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveItemsRCLAStudioProcessAutomationRouteRoute =
  ArchiveItemsRCLAStudioProcessAutomationRouteRouteImport.update({
    id: '/archive/_items/RCLA-studio-process-automation',
    path: '/archive/RCLA-studio-process-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchiveItemsHK19Hack19RouteRoute =
  ArchiveItemsHK19Hack19RouteRouteImport.update({
    id: '/archive/_items/HK19-hack19',
    path: '/archive/HK19-hack19',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchiveItemsDVISDataVisShowcaseRouteRoute =
  ArchiveItemsDVISDataVisShowcaseRouteRouteImport.update({
    id: '/archive/_items/DVIS-data-vis-showcase',
    path: '/archive/DVIS-data-vis-showcase',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchiveItemsCRSSCreditSuisseOsaRouteRoute =
  ArchiveItemsCRSSCreditSuisseOsaRouteRouteImport.update({
    id: '/archive/_items/CRSS-credit-suisse-osa',
    path: '/archive/CRSS-credit-suisse-osa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchiveItemsCEPLCarderRouteRoute =
  ArchiveItemsCEPLCarderRouteRouteImport.update({
    id: '/archive/_items/CEPL-carder',
    path: '/archive/CEPL-carder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchiveItemsALRNAileronRouteRoute =
  ArchiveItemsALRNAileronRouteRouteImport.update({
    id: '/archive/_items/ALRN-aileron',
    path: '/archive/ALRN-aileron',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills': typeof SkillsRouteRouteWithChildren
  '/debug': typeof DebugRoute
  '/showcase': typeof ShowcaseRoute
  '/library': typeof LibraryIndexRouteRoute
  '/experimental/book1': typeof ExperimentalBook1Route
  '/experimental/book2': typeof ExperimentalBook2Route
  '/library/multitenancy': typeof LibraryMultitenancyRoute
  '/profile/academic': typeof ProfileAcademicRoute
  '/skills/data': typeof SkillsDataRoute
  '/skills/design': typeof SkillsDesignRoute
  '/skills/enterprise': typeof SkillsEnterpriseRoute
  '/skills/technology': typeof SkillsTechnologyRoute
  '/about': typeof AboutIndexRoute
  '/archive': typeof ArchiveIndexRoute
  '/legal': typeof LegalIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/archive/ALRN-aileron': typeof ArchiveItemsALRNAileronRouteRoute
  '/archive/CEPL-carder': typeof ArchiveItemsCEPLCarderRouteRoute
  '/archive/CRSS-credit-suisse-osa': typeof ArchiveItemsCRSSCreditSuisseOsaRouteRoute
  '/archive/DVIS-data-vis-showcase': typeof ArchiveItemsDVISDataVisShowcaseRouteRoute
  '/archive/HK19-hack19': typeof ArchiveItemsHK19Hack19RouteRoute
  '/archive/RCLA-studio-process-automation': typeof ArchiveItemsRCLAStudioProcessAutomationRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/showcase': typeof ShowcaseRoute
  '/library': typeof LibraryIndexRouteRoute
  '/experimental/book1': typeof ExperimentalBook1Route
  '/experimental/book2': typeof ExperimentalBook2Route
  '/library/multitenancy': typeof LibraryMultitenancyRoute
  '/profile/academic': typeof ProfileAcademicRoute
  '/skills/data': typeof SkillsDataRoute
  '/skills/design': typeof SkillsDesignRoute
  '/skills/enterprise': typeof SkillsEnterpriseRoute
  '/skills/technology': typeof SkillsTechnologyRoute
  '/about': typeof AboutIndexRoute
  '/archive': typeof ArchiveIndexRoute
  '/legal': typeof LegalIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/archive/ALRN-aileron': typeof ArchiveItemsALRNAileronRouteRoute
  '/archive/CEPL-carder': typeof ArchiveItemsCEPLCarderRouteRoute
  '/archive/CRSS-credit-suisse-osa': typeof ArchiveItemsCRSSCreditSuisseOsaRouteRoute
  '/archive/DVIS-data-vis-showcase': typeof ArchiveItemsDVISDataVisShowcaseRouteRoute
  '/archive/HK19-hack19': typeof ArchiveItemsHK19Hack19RouteRoute
  '/archive/RCLA-studio-process-automation': typeof ArchiveItemsRCLAStudioProcessAutomationRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skills': typeof SkillsRouteRouteWithChildren
  '/debug': typeof DebugRoute
  '/showcase': typeof ShowcaseRoute
  '/library/': typeof LibraryIndexRouteRoute
  '/experimental/book1': typeof ExperimentalBook1Route
  '/experimental/book2': typeof ExperimentalBook2Route
  '/library/multitenancy': typeof LibraryMultitenancyRoute
  '/profile/academic': typeof ProfileAcademicRoute
  '/skills/data': typeof SkillsDataRoute
  '/skills/design': typeof SkillsDesignRoute
  '/skills/enterprise': typeof SkillsEnterpriseRoute
  '/skills/technology': typeof SkillsTechnologyRoute
  '/about/': typeof AboutIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/archive/_items/ALRN-aileron': typeof ArchiveItemsALRNAileronRouteRoute
  '/archive/_items/CEPL-carder': typeof ArchiveItemsCEPLCarderRouteRoute
  '/archive/_items/CRSS-credit-suisse-osa': typeof ArchiveItemsCRSSCreditSuisseOsaRouteRoute
  '/archive/_items/DVIS-data-vis-showcase': typeof ArchiveItemsDVISDataVisShowcaseRouteRoute
  '/archive/_items/HK19-hack19': typeof ArchiveItemsHK19Hack19RouteRoute
  '/archive/_items/RCLA-studio-process-automation': typeof ArchiveItemsRCLAStudioProcessAutomationRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/skills'
    | '/debug'
    | '/showcase'
    | '/library'
    | '/experimental/book1'
    | '/experimental/book2'
    | '/library/multitenancy'
    | '/profile/academic'
    | '/skills/data'
    | '/skills/design'
    | '/skills/enterprise'
    | '/skills/technology'
    | '/about'
    | '/archive'
    | '/legal'
    | '/skills/'
    | '/archive/ALRN-aileron'
    | '/archive/CEPL-carder'
    | '/archive/CRSS-credit-suisse-osa'
    | '/archive/DVIS-data-vis-showcase'
    | '/archive/HK19-hack19'
    | '/archive/RCLA-studio-process-automation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/showcase'
    | '/library'
    | '/experimental/book1'
    | '/experimental/book2'
    | '/library/multitenancy'
    | '/profile/academic'
    | '/skills/data'
    | '/skills/design'
    | '/skills/enterprise'
    | '/skills/technology'
    | '/about'
    | '/archive'
    | '/legal'
    | '/skills'
    | '/archive/ALRN-aileron'
    | '/archive/CEPL-carder'
    | '/archive/CRSS-credit-suisse-osa'
    | '/archive/DVIS-data-vis-showcase'
    | '/archive/HK19-hack19'
    | '/archive/RCLA-studio-process-automation'
  id:
    | '__root__'
    | '/'
    | '/skills'
    | '/debug'
    | '/showcase'
    | '/library/'
    | '/experimental/book1'
    | '/experimental/book2'
    | '/library/multitenancy'
    | '/profile/academic'
    | '/skills/data'
    | '/skills/design'
    | '/skills/enterprise'
    | '/skills/technology'
    | '/about/'
    | '/archive/'
    | '/legal/'
    | '/skills/'
    | '/archive/_items/ALRN-aileron'
    | '/archive/_items/CEPL-carder'
    | '/archive/_items/CRSS-credit-suisse-osa'
    | '/archive/_items/DVIS-data-vis-showcase'
    | '/archive/_items/HK19-hack19'
    | '/archive/_items/RCLA-studio-process-automation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsRouteRoute: typeof SkillsRouteRouteWithChildren
  DebugRoute: typeof DebugRoute
  ShowcaseRoute: typeof ShowcaseRoute
  LibraryIndexRouteRoute: typeof LibraryIndexRouteRoute
  ExperimentalBook1Route: typeof ExperimentalBook1Route
  ExperimentalBook2Route: typeof ExperimentalBook2Route
  LibraryMultitenancyRoute: typeof LibraryMultitenancyRoute
  ProfileAcademicRoute: typeof ProfileAcademicRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  ArchiveItemsALRNAileronRouteRoute: typeof ArchiveItemsALRNAileronRouteRoute
  ArchiveItemsCEPLCarderRouteRoute: typeof ArchiveItemsCEPLCarderRouteRoute
  ArchiveItemsCRSSCreditSuisseOsaRouteRoute: typeof ArchiveItemsCRSSCreditSuisseOsaRouteRoute
  ArchiveItemsDVISDataVisShowcaseRouteRoute: typeof ArchiveItemsDVISDataVisShowcaseRouteRoute
  ArchiveItemsHK19Hack19RouteRoute: typeof ArchiveItemsHK19Hack19RouteRoute
  ArchiveItemsRCLAStudioProcessAutomationRouteRoute: typeof ArchiveItemsRCLAStudioProcessAutomationRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof SkillsRouteRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/technology': {
      id: '/skills/technology'
      path: '/technology'
      fullPath: '/skills/technology'
      preLoaderRoute: typeof SkillsTechnologyRouteImport
      parentRoute: typeof SkillsRouteRoute
    }
    '/skills/enterprise': {
      id: '/skills/enterprise'
      path: '/enterprise'
      fullPath: '/skills/enterprise'
      preLoaderRoute: typeof SkillsEnterpriseRouteImport
      parentRoute: typeof SkillsRouteRoute
    }
    '/skills/design': {
      id: '/skills/design'
      path: '/design'
      fullPath: '/skills/design'
      preLoaderRoute: typeof SkillsDesignRouteImport
      parentRoute: typeof SkillsRouteRoute
    }
    '/skills/data': {
      id: '/skills/data'
      path: '/data'
      fullPath: '/skills/data'
      preLoaderRoute: typeof SkillsDataRouteImport
      parentRoute: typeof SkillsRouteRoute
    }
    '/profile/academic': {
      id: '/profile/academic'
      path: '/profile/academic'
      fullPath: '/profile/academic'
      preLoaderRoute: typeof ProfileAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/multitenancy': {
      id: '/library/multitenancy'
      path: '/library/multitenancy'
      fullPath: '/library/multitenancy'
      preLoaderRoute: typeof LibraryMultitenancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experimental/book2': {
      id: '/experimental/book2'
      path: '/experimental/book2'
      fullPath: '/experimental/book2'
      preLoaderRoute: typeof ExperimentalBook2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experimental/book1': {
      id: '/experimental/book1'
      path: '/experimental/book1'
      fullPath: '/experimental/book1'
      preLoaderRoute: typeof ExperimentalBook1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/_items/RCLA-studio-process-automation': {
      id: '/archive/_items/RCLA-studio-process-automation'
      path: '/archive/RCLA-studio-process-automation'
      fullPath: '/archive/RCLA-studio-process-automation'
      preLoaderRoute: typeof ArchiveItemsRCLAStudioProcessAutomationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/_items/HK19-hack19': {
      id: '/archive/_items/HK19-hack19'
      path: '/archive/HK19-hack19'
      fullPath: '/archive/HK19-hack19'
      preLoaderRoute: typeof ArchiveItemsHK19Hack19RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/_items/DVIS-data-vis-showcase': {
      id: '/archive/_items/DVIS-data-vis-showcase'
      path: '/archive/DVIS-data-vis-showcase'
      fullPath: '/archive/DVIS-data-vis-showcase'
      preLoaderRoute: typeof ArchiveItemsDVISDataVisShowcaseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/_items/CRSS-credit-suisse-osa': {
      id: '/archive/_items/CRSS-credit-suisse-osa'
      path: '/archive/CRSS-credit-suisse-osa'
      fullPath: '/archive/CRSS-credit-suisse-osa'
      preLoaderRoute: typeof ArchiveItemsCRSSCreditSuisseOsaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/_items/CEPL-carder': {
      id: '/archive/_items/CEPL-carder'
      path: '/archive/CEPL-carder'
      fullPath: '/archive/CEPL-carder'
      preLoaderRoute: typeof ArchiveItemsCEPLCarderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/_items/ALRN-aileron': {
      id: '/archive/_items/ALRN-aileron'
      path: '/archive/ALRN-aileron'
      fullPath: '/archive/ALRN-aileron'
      preLoaderRoute: typeof ArchiveItemsALRNAileronRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SkillsRouteRouteChildren {
  SkillsDataRoute: typeof SkillsDataRoute
  SkillsDesignRoute: typeof SkillsDesignRoute
  SkillsEnterpriseRoute: typeof SkillsEnterpriseRoute
  SkillsTechnologyRoute: typeof SkillsTechnologyRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

const SkillsRouteRouteChildren: SkillsRouteRouteChildren = {
  SkillsDataRoute: SkillsDataRoute,
  SkillsDesignRoute: SkillsDesignRoute,
  SkillsEnterpriseRoute: SkillsEnterpriseRoute,
  SkillsTechnologyRoute: SkillsTechnologyRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}

const SkillsRouteRouteWithChildren = SkillsRouteRoute._addFileChildren(
  SkillsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsRouteRoute: SkillsRouteRouteWithChildren,
  DebugRoute: DebugRoute,
  ShowcaseRoute: ShowcaseRoute,
  LibraryIndexRouteRoute: LibraryIndexRouteRoute,
  ExperimentalBook1Route: ExperimentalBook1Route,
  ExperimentalBook2Route: ExperimentalBook2Route,
  LibraryMultitenancyRoute: LibraryMultitenancyRoute,
  ProfileAcademicRoute: ProfileAcademicRoute,
  AboutIndexRoute: AboutIndexRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  ArchiveItemsALRNAileronRouteRoute: ArchiveItemsALRNAileronRouteRoute,
  ArchiveItemsCEPLCarderRouteRoute: ArchiveItemsCEPLCarderRouteRoute,
  ArchiveItemsCRSSCreditSuisseOsaRouteRoute:
    ArchiveItemsCRSSCreditSuisseOsaRouteRoute,
  ArchiveItemsDVISDataVisShowcaseRouteRoute:
    ArchiveItemsDVISDataVisShowcaseRouteRoute,
  ArchiveItemsHK19Hack19RouteRoute: ArchiveItemsHK19Hack19RouteRoute,
  ArchiveItemsRCLAStudioProcessAutomationRouteRoute:
    ArchiveItemsRCLAStudioProcessAutomationRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
